<?php

return [
    /*
    |--------------------------------------------------------------------------
    | Generated certificate storage
    |--------------------------------------------------------------------------
    | Use a shared disk (for example S3) when more than one application
    | instance serves traffic. Artifacts are served through the revocation-aware
    | public credential route and must not have a durable public object URL.
    */
    'disk' => env('CERTIFICATE_DISK', env('FILESYSTEM_PUBLIC_DISK', 'public')),
    /*
    |--------------------------------------------------------------------------
    | Certificate template image
    |--------------------------------------------------------------------------
    | Path to the background PNG/JPG that serves as the certificate canvas.
    | All dynamic text and QR code are drawn on top of this image.
    */
    'template_path' => env('CERTIFICATE_TEMPLATE_PATH', null) ?: public_path('images/certificate_template_v2.png'),

    /*
    |--------------------------------------------------------------------------
    | Legacy deep-link base URL
    |--------------------------------------------------------------------------
    | Kept only for older deployments. New certificates use the permanent
    | /c/{publicId} verification route generated by Laravel.
    */
    'deep_link_base' => env('CERTIFICATE_DEEP_LINK_BASE'),

    /*
    |--------------------------------------------------------------------------
    | Font paths
    |--------------------------------------------------------------------------
    | Cairo variable font (599 KB) covers all weights including bold and has
    | complete Arabic + Latin glyph sets.
    */
    'font_regular' => env('CERTIFICATE_FONT_PATH', resource_path('fonts/Cairo.ttf')),
    'font_bold'    => env('CERTIFICATE_FONT_BOLD_PATH', resource_path('fonts/Cairo.ttf')),

    /*
    |--------------------------------------------------------------------------
    | Date format
    |--------------------------------------------------------------------------
    */
    'date_format' => 'j F Y',

    /*
    |--------------------------------------------------------------------------
    | Achievement text
    |--------------------------------------------------------------------------
    | Every course selects one approved wording key. The resolved key and text
    | are copied to the certificate row when it is issued, so later editorial
    | changes never rewrite an existing credential.
    */
    'default_text_template_key' => 'completion',
    'text_templates' => [
        'completion' => [
            'label' => 'إتمام الكورس',
            'description' => 'مناسبة لمعظم الكورسات',
            'text' => 'تقديرًا لإتمام متطلبات كورس',
        ],
        'knowledge' => [
            'label' => 'المعرفة',
            'description' => 'مناسبة للكورسات المعرفية والنظرية',
            'text' => 'تقديرًا لإتمام المسار المعرفي لكورس',
        ],
        'applied' => [
            'label' => 'التطبيق العملي',
            'description' => 'مناسبة للكورسات التي تجمع التعلم بالتطبيق',
            'text' => 'تقديرًا لإتمام المتطلبات التطبيقية لكورس',
        ],
        'projects' => [
            'label' => 'المشروعات',
            'description' => 'مناسبة للكورسات التي تعتمد على مشروعات العبور',
            'text' => 'تقديرًا لإنجاز مشروعات كورس',
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Text overlay positions
    |--------------------------------------------------------------------------
    | Coordinates are expressed as decimal fractions of the template image
    | dimensions (0.0 – 1.0). This makes them resolution-independent.
    | Font sizes are absolute pixel values.
    |
    | Default values are tuned for the 1200 × 900 certificate template.
    */
    'text_positions' => [

        // Student name — centred below the Arabic recipient label.
        'name' => [
            'x'     => 0.50,
            'y'     => 0.385,
            'size'  => 38,
            'color' => '#08172F',
        ],

        // Course name — the final line in the central credential hierarchy.
        'course' => [
            'x'     => 0.50,
            'y'     => 0.590,
            'size'  => 27,
            'color' => '#08172F',
        ],

        // Certificate ID — below its Arabic label at the lower right.
        'cert_id' => [
            'x'     => 0.885,
            'y'     => 0.952,
            // A UUID is the externally verifiable credential identifier.
            'size'  => 8,
            'color' => '#08172F',
        ],

        // Immutable achievement wording selected for this issued credential.
        'achievement' => [
            'x'     => 0.50,
            'y'     => 0.505,
            'size'  => 18,
            'color' => '#41506A',
        ],

        // Date — centred below its Arabic label at the lower right.
        'date' => [
            'x'     => 0.823,
            'y'     => 0.800,
            'size'  => 14,
            'color' => '#08172F',
        ],

        // QR code — centred inside the fixed verification frame.
        'qr_code' => [
            'x'    => 0.160,
            'y'    => 0.804,
            'size' => 132,
        ],
    ],
];
